FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY ./admin/package*.json ./

# Install dependencies
RUN npm install

# Copy shared directory
COPY ./shared ./shared

# Copy app code
COPY ./admin .

EXPOSE 3000

CMD ["npx", "next", "dev", "--port", "3000", "--hostname", "0.0.0.0"]
